{
 "title": "Gopher app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Upload endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gopher_upload_requests_total{code=\"302\"}[1m])",
     "legendFormat": "Success requests"
    },
    {
     "expr": "increase(gopher_upload_requests_total{code=\"400\"}[1m])",
     "legendFormat": "Error requests"
    }
   ]
  },
  {
   "title": "Hello endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gopher_hello_requests_total{code=\"200\"}[1m])",
     "legendFormat": "Success requests"
    },
    {
     "expr": "increase(gopher_hello_requests_total{code=\"503\"}[1m])",
     "legendFormat": "Error requests"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"gopher-app\"} |= \"error\")[5m]))",
     "legendFormat": "error logs"
    },
    {
     "expr": "sum(count_over_time(({job=\"gopher-app\"} |= \"warning\")[5m]))",
     "legendFormat": "warning logs"
    }
   ]
  }
 ]
}